//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogueForest.Localization.Strings {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DialogueForest.Localization.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DialogueForest.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string ButtonCancelText {
            get {
                return ResourceManager.GetString("ButtonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        public static string ButtonCreateText {
            get {
                return ResourceManager.GetString("ButtonCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string ButtonDeleteText {
            get {
                return ResourceManager.GetString("ButtonDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pick a File....
        /// </summary>
        public static string ButtonFileText {
            get {
                return ResourceManager.GetString("ButtonFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pick a Folder....
        /// </summary>
        public static string ButtonFolderText {
            get {
                return ResourceManager.GetString("ButtonFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string ButtonNoText {
            get {
                return ResourceManager.GetString("ButtonNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        public static string ButtonOKText {
            get {
                return ResourceManager.GetString("ButtonOKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string ButtonYesText {
            get {
                return ResourceManager.GetString("ButtonYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete this Text?.
        /// </summary>
        public static string ContentDialogDeleteDialogue {
            get {
                return ResourceManager.GetString("ContentDialogDeleteDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete this Reply?.
        /// </summary>
        public static string ContentDialogDeleteReply {
            get {
                return ResourceManager.GetString("ContentDialogDeleteReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete this Tree?.
        /// </summary>
        public static string ContentDialogDeleteTree {
            get {
                return ResourceManager.GetString("ContentDialogDeleteTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All its nodes will be moved to Trash..
        /// </summary>
        public static string ContentDialogDeleteTreeDesc {
            get {
                return ResourceManager.GetString("ContentDialogDeleteTreeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete this Dialogue?.
        /// </summary>
        public static string ContentDialogueDeleteNode {
            get {
                return ResourceManager.GetString("ContentDialogueDeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It will be permanently deleted!.
        /// </summary>
        public static string ContentDialogWillBePermaDeleted {
            get {
                return ResourceManager.GetString("ContentDialogWillBePermaDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete permanently.
        /// </summary>
        public static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Linked By.
        /// </summary>
        public static string ContextMenuLinkedBy {
            get {
                return ResourceManager.GetString("ContextMenuLinkedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Links To.
        /// </summary>
        public static string ContextMenuLinksTo {
            get {
                return ResourceManager.GetString("ContextMenuLinksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move to another Tree.
        /// </summary>
        public static string ContextMenuMove {
            get {
                return ResourceManager.GetString("ContextMenuMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pin.
        /// </summary>
        public static string ContextMenuPin {
            get {
                return ResourceManager.GetString("ContextMenuPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move to Trash.
        /// </summary>
        public static string ContextMenuTrash {
            get {
                return ResourceManager.GetString("ContextMenuTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unpin.
        /// </summary>
        public static string ContextMenuUnpin {
            get {
                return ResourceManager.GetString("ContextMenuUnpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} dialogues.
        /// </summary>
        public static string CountDialogues {
            get {
                return ResourceManager.GetString("CountDialogues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} words.
        /// </summary>
        public static string CountWords {
            get {
                return ResourceManager.GetString("CountWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Let&apos;s try to write {0} words today!.
        /// </summary>
        public static string DailyNotificationDesc {
            get {
                return ResourceManager.GetString("DailyNotificationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open DialogueForest to pen your story!.
        /// </summary>
        public static string DailyNotificationDescNoTrack {
            get {
                return ResourceManager.GetString("DailyNotificationDescNoTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time to write some dialogue.
        /// </summary>
        public static string DailyNotificationTitle {
            get {
                return ResourceManager.GetString("DailyNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Good job on meeting your goal for today!.
        /// </summary>
        public static string DailyObjectiveStreakDesc {
            get {
                return ResourceManager.GetString("DailyObjectiveStreakDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✨ A {0}-day streak!.
        /// </summary>
        public static string DailyObjectiveStreakTitle {
            get {
                return ResourceManager.GetString("DailyObjectiveStreakTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a piece of Dialogue.
        /// </summary>
        public static string EditorAddDialogue {
            get {
                return ResourceManager.GetString("EditorAddDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a reply Prompt.
        /// </summary>
        public static string EditorAddReply {
            get {
                return ResourceManager.GetString("EditorAddReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bold.
        /// </summary>
        public static string EditorBold {
            get {
                return ResourceManager.GetString("EditorBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Character.
        /// </summary>
        public static string EditorCharacterPlaceholder {
            get {
                return ResourceManager.GetString("EditorCharacterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Dialogue portion.
        /// </summary>
        public static string EditorDeleteDialogue {
            get {
                return ResourceManager.GetString("EditorDeleteDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Reply.
        /// </summary>
        public static string EditorDeleteReply {
            get {
                return ResourceManager.GetString("EditorDeleteReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you define custom metadata keys in.
        /// </summary>
        public static string EditorEmptyMetadata1 {
            get {
                return ResourceManager.GetString("EditorEmptyMetadata1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , you will be able to set values for them here..
        /// </summary>
        public static string EditorEmptyMetadata2 {
            get {
                return ResourceManager.GetString("EditorEmptyMetadata2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replies to this dialogue will show up here, if you add any..
        /// </summary>
        public static string EditorEmptyReplies {
            get {
                return ResourceManager.GetString("EditorEmptyReplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text Color.
        /// </summary>
        public static string EditorFontColor {
            get {
                return ResourceManager.GetString("EditorFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dialogue.
        /// </summary>
        public static string EditorHeaderDialogue {
            get {
                return ResourceManager.GetString("EditorHeaderDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string EditorHeaderMetadata {
            get {
                return ResourceManager.GetString("EditorHeaderMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prompts.
        /// </summary>
        public static string EditorHeaderReply {
            get {
                return ResourceManager.GetString("EditorHeaderReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italic.
        /// </summary>
        public static string EditorItalic {
            get {
                return ResourceManager.GetString("EditorItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accusam consetetur ut accusam et gubergren augue diam enim dolor at nulla ea ipsum diam et lobortis. Et no rebum odio takimata nulla nisl takimata iriure sit aliquyam eirmod nulla sit. Magna justo consetetur takimata..
        /// </summary>
        public static string EditorPlaceholderText {
            get {
                return ResourceManager.GetString("EditorPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to Linked Dialogue.
        /// </summary>
        public static string EditorReplyGoToLinked {
            get {
                return ResourceManager.GetString("EditorReplyGoToLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Linked to:.
        /// </summary>
        public static string EditorReplyLinkedTo {
            get {
                return ResourceManager.GetString("EditorReplyLinkedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magna ea feugiat labore diam diam assum amet nibh vero sea eirmod magna takimata eum illum. Labore et nonumy vulputate lorem zzril erat kasd eu no sed laoreet duo labore et diam eos..
        /// </summary>
        public static string EditorReplyPlaceholderText {
            get {
                return ResourceManager.GetString("EditorReplyPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show in Tree.
        /// </summary>
        public static string EditorShowInTree {
            get {
                return ResourceManager.GetString("EditorShowInTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Underline.
        /// </summary>
        public static string EditorUnderline {
            get {
                return ResourceManager.GetString("EditorUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have unsaved changes.
        /// </summary>
        public static string EditorUnsavedChanges {
            get {
                return ResourceManager.GetString("EditorUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Dialogue Nodes will show up here. 
        ///You can create Nodes in the Dialogue Trees on the left side..
        /// </summary>
        public static string EmptyViewDocumentsDesc {
            get {
                return ResourceManager.GetString("EmptyViewDocumentsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Let&apos;s get writing!.
        /// </summary>
        public static string EmptyViewDocumentsTitle {
            get {
                return ResourceManager.GetString("EmptyViewDocumentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notes are pieces of dialogue that aren&apos;t 
        ///included in your final Export. 
        ///Use them to store ideas or drafts!.
        /// </summary>
        public static string EmptyViewNotesDesc {
            get {
                return ResourceManager.GetString("EmptyViewNotesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have no Notes..
        /// </summary>
        public static string EmptyViewNotesTitle {
            get {
                return ResourceManager.GetString("EmptyViewNotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can pin Dialogue Nodes to find them again easily!
        ///They&apos;ll show up here when you do..
        /// </summary>
        public static string EmptyViewPinsDesc {
            get {
                return ResourceManager.GetString("EmptyViewPinsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nothing on the pinboard..
        /// </summary>
        public static string EmptyViewPinsTitle {
            get {
                return ResourceManager.GetString("EmptyViewPinsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleted Dialogue Nodes will end up here..
        /// </summary>
        public static string EmptyViewTrashDesc {
            get {
                return ResourceManager.GetString("EmptyViewTrashDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nothing&apos;s trashed...yet..
        /// </summary>
        public static string EmptyViewTrashTitle {
            get {
                return ResourceManager.GetString("EmptyViewTrashTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Dialogue will show up here.
        ///Click on the &quot;+&quot; button to add some!.
        /// </summary>
        public static string EmptyViewTreeDesc {
            get {
                return ResourceManager.GetString("EmptyViewTreeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Talkin&apos; yet..
        /// </summary>
        public static string EmptyViewTreeTitle {
            get {
                return ResourceManager.GetString("EmptyViewTreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: {0}.
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File name is null or empty. Specify a valid file name.
        /// </summary>
        public static string ExceptionSettingsStorageExtensionsFileNameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionSettingsStorageExtensionsFileNameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All pages opened in a new window must subscribe to the Released Event..
        /// </summary>
        public static string ExceptionViewLifeTimeControlMissingReleasedSubscription {
            get {
                return ResourceManager.GetString("ExceptionViewLifeTimeControlMissingReleasedSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This view is being disposed..
        /// </summary>
        public static string ExceptionViewLifeTimeControlViewDisposal {
            get {
                return ResourceManager.GetString("ExceptionViewLifeTimeControlViewDisposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export All Dialogue.
        /// </summary>
        public static string ExportActionButtonText {
            get {
                return ResourceManager.GetString("ExportActionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose which format your Dialogue text will be exported as..
        /// </summary>
        public static string ExportConversionDesc {
            get {
                return ResourceManager.GetString("ExportConversionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text Format.
        /// </summary>
        public static string ExportConversionParameter {
            get {
                return ResourceManager.GetString("ExportConversionParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSON Export Location.
        /// </summary>
        public static string ExportFileLocation {
            get {
                return ResourceManager.GetString("ExportFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exporting... Please wait warmly..
        /// </summary>
        public static string ExportOperationInProgress {
            get {
                return ResourceManager.GetString("ExportOperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If enabled, we&apos;ll export a separate JSON for each Dialogue Tree..
        /// </summary>
        public static string ExportSeparateFilesDesc {
            get {
                return ResourceManager.GetString("ExportSeparateFilesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create separate JSON files.
        /// </summary>
        public static string ExportSeparateFilesTitle {
            get {
                return ResourceManager.GetString("ExportSeparateFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à David Bowie is credited with playing the Stylophone on his 1969 debut hit song &quot;Space Oddity&quot; and also for his 2002 album Heathen track titled &quot;Slip Away,&quot; as well as on the song &quot;Heathen (The Rays)&quot;..
        /// </summary>
        public static string FirstRunFlavorText {
            get {
                return ResourceManager.GetString("FirstRunFlavorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To get started, please visit the Settings page to key in your MPD server&apos;s URL and port.
        ///Keep in mind Stylophone can send usage data to help diagnose bugs. 
        ///If you&apos;re not okay with this, you can disable telemetry in the Settings.
        ///Hope you enjoy using the application!  
        ///.
        /// </summary>
        public static string FirstRunText {
            get {
                return ResourceManager.GetString("FirstRunText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to DialogueForest!.
        /// </summary>
        public static string FirstRunTitle {
            get {
                return ResourceManager.GetString("FirstRunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        public static string NavigationExport {
            get {
                return ResourceManager.GetString("NavigationExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        public static string NavigationFile {
            get {
                return ResourceManager.GetString("NavigationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Forest.
        /// </summary>
        public static string NavigationNew {
            get {
                return ResourceManager.GetString("NavigationNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Tree.
        /// </summary>
        public static string NavigationNewTree {
            get {
                return ResourceManager.GetString("NavigationNewTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notes.
        /// </summary>
        public static string NavigationNotes {
            get {
                return ResourceManager.GetString("NavigationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        public static string NavigationOpen {
            get {
                return ResourceManager.GetString("NavigationOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Pins.
        /// </summary>
        public static string NavigationPins {
            get {
                return ResourceManager.GetString("NavigationPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string NavigationSave {
            get {
                return ResourceManager.GetString("NavigationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string NavigationSettings {
            get {
                return ResourceManager.GetString("NavigationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trash.
        /// </summary>
        public static string NavigationTrash {
            get {
                return ResourceManager.GetString("NavigationTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dialogue Trees.
        /// </summary>
        public static string NavigationTrees {
            get {
                return ResourceManager.GetString("NavigationTrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Nodes.
        /// </summary>
        public static string NoNodesText {
            get {
                return ResourceManager.GetString("NoNodesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Failed! See the below notification for details..
        /// </summary>
        public static string NotificationExportFailed {
            get {
                return ResourceManager.GetString("NotificationExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exported Successfully!.
        /// </summary>
        public static string NotificationExportSuccess {
            get {
                return ResourceManager.GetString("NotificationExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pinned!.
        /// </summary>
        public static string NotificationPinned {
            get {
                return ResourceManager.GetString("NotificationPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trashed!.
        /// </summary>
        public static string NotificationTrashed {
            get {
                return ResourceManager.GetString("NotificationTrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unpinned!.
        /// </summary>
        public static string NotificationUnpinned {
            get {
                return ResourceManager.GetString("NotificationUnpinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Off.
        /// </summary>
        public static string OffText {
            get {
                return ResourceManager.GetString("OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On.
        /// </summary>
        public static string OnText {
            get {
                return ResourceManager.GetString("OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thanks for using DialogueForest! Would you like to rate the app on the Store? 
        ///(We won&apos;t ask again. 🙏).
        /// </summary>
        public static string RateAppPromptText {
            get {
                return ResourceManager.GetString("RateAppPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rate the Application.
        /// </summary>
        public static string RateAppPromptTitle {
            get {
                return ResourceManager.GetString("RateAppPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search....
        /// </summary>
        public static string SearchPlaceholderText {
            get {
                return ResourceManager.GetString("SearchPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tracks.
        /// </summary>
        public static string SearchTracksToggle {
            get {
                return ResourceManager.GetString("SearchTracksToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search Nodes....
        /// </summary>
        public static string SearchTreePlaceholderText {
            get {
                return ResourceManager.GetString("SearchTreePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About this application.
        /// </summary>
        public static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An opinionated Dialogue Writer for Games..
        /// </summary>
        public static string SettingsAboutText {
            get {
                return ResourceManager.GetString("SettingsAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analytics.
        /// </summary>
        public static string SettingsAnalytics {
            get {
                return ResourceManager.GetString("SettingsAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow DialogueForest to send crash and analytics reports.
        /// </summary>
        public static string SettingsAnalyticsText {
            get {
                return ResourceManager.GetString("SettingsAnalyticsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This setting will apply after restarting the app..
        /// </summary>
        public static string SettingsApplyOnRestart {
            get {
                return ResourceManager.GetString("SettingsApplyOnRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add character.
        /// </summary>
        public static string SettingsCharacterAdd {
            get {
                return ResourceManager.GetString("SettingsCharacterAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove character.
        /// </summary>
        public static string SettingsCharacterDelete {
            get {
                return ResourceManager.GetString("SettingsCharacterDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pre-defined Characters.
        /// </summary>
        public static string SettingsCharactersHeader {
            get {
                return ResourceManager.GetString("SettingsCharactersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à These will appear as quick presets in your Dialogue Nodes..
        /// </summary>
        public static string SettingsCharactersText {
            get {
                return ResourceManager.GetString("SettingsCharactersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personalization.
        /// </summary>
        public static string SettingsCustomization {
            get {
                return ResourceManager.GetString("SettingsCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database and Album Art.
        /// </summary>
        public static string SettingsDatabase {
            get {
                return ResourceManager.GetString("SettingsDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current Dialogue Forest.
        /// </summary>
        public static string SettingsForest {
            get {
                return ResourceManager.GetString("SettingsForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source Code, License and Privacy Statement.
        /// </summary>
        public static string SettingsGithub {
            get {
                return ResourceManager.GetString("SettingsGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://github.com/Difegue/DialogueForest.
        /// </summary>
        public static string SettingsGithubLink {
            get {
                return ResourceManager.GetString("SettingsGithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add property.
        /// </summary>
        public static string SettingsMetadataAdd {
            get {
                return ResourceManager.GetString("SettingsMetadataAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove custom property.
        /// </summary>
        public static string SettingsMetadataDelete {
            get {
                return ResourceManager.GetString("SettingsMetadataDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom Properties.
        /// </summary>
        public static string SettingsMetadataHeader {
            get {
                return ResourceManager.GetString("SettingsMetadataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key.
        /// </summary>
        public static string SettingsMetadataKey {
            get {
                return ResourceManager.GetString("SettingsMetadataKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Property fields will appear on every Dialogue Node for you to input additional information..
        /// </summary>
        public static string SettingsMetadataText {
            get {
                return ResourceManager.GetString("SettingsMetadataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string SettingsMetadataType {
            get {
                return ResourceManager.GetString("SettingsMetadataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boolean.
        /// </summary>
        public static string SettingsMetadataTypeBool {
            get {
                return ResourceManager.GetString("SettingsMetadataTypeBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color.
        /// </summary>
        public static string SettingsMetadataTypeColor {
            get {
                return ResourceManager.GetString("SettingsMetadataTypeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preexisting values.
        /// </summary>
        public static string SettingsMetadataTypeEnum {
            get {
                return ResourceManager.GetString("SettingsMetadataTypeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à String.
        /// </summary>
        public static string SettingsMetadataTypeString {
            get {
                return ResourceManager.GetString("SettingsMetadataTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Daily reminder.
        /// </summary>
        public static string SettingsNotification {
            get {
                return ResourceManager.GetString("SettingsNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sends one notification each day to remind you to open the app..
        /// </summary>
        public static string SettingsNotificationDesc {
            get {
                return ResourceManager.GetString("SettingsNotificationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send at:.
        /// </summary>
        public static string SettingsNotificationSendAt {
            get {
                return ResourceManager.GetString("SettingsNotificationSendAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application Theme.
        /// </summary>
        public static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dark.
        /// </summary>
        public static string SettingsThemeDark {
            get {
                return ResourceManager.GetString("SettingsThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System default.
        /// </summary>
        public static string SettingsThemeDefault {
            get {
                return ResourceManager.GetString("SettingsThemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Light.
        /// </summary>
        public static string SettingsThemeLight {
            get {
                return ResourceManager.GetString("SettingsThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UI Density.
        /// </summary>
        public static string SettingsUIDensity {
            get {
                return ResourceManager.GetString("SettingsUIDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compact.
        /// </summary>
        public static string SettingsUIDensityCompact {
            get {
                return ResourceManager.GetString("SettingsUIDensityCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normal.
        /// </summary>
        public static string SettingsUIDensityNormal {
            get {
                return ResourceManager.GetString("SettingsUIDensityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set a daily goal to encourage writing..
        /// </summary>
        public static string SettingsWordDesc {
            get {
                return ResourceManager.GetString("SettingsWordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Daily objective &amp; Reminders.
        /// </summary>
        public static string SettingsWordHeader {
            get {
                return ResourceManager.GetString("SettingsWordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Daily word objective.
        /// </summary>
        public static string SettingsWordObjective {
            get {
                return ResourceManager.GetString("SettingsWordObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Track word count.
        /// </summary>
        public static string SettingsWordTrack {
            get {
                return ResourceManager.GetString("SettingsWordTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Tree.
        /// </summary>
        public static string TreeNameDialogDefaultName {
            get {
                return ResourceManager.GetString("TreeNameDialogDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Orange Tree.
        /// </summary>
        public static string TreeNameDialogPlaceholder {
            get {
                return ResourceManager.GetString("TreeNameDialogPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Give a name to your freshly planted Tree! 
        ///You can always change this later..
        /// </summary>
        public static string TreeNameDialogText {
            get {
                return ResourceManager.GetString("TreeNameDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Dialogue Tree.
        /// </summary>
        public static string TreeNameDialogTitle {
            get {
                return ResourceManager.GetString("TreeNameDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Dialogue Node.
        /// </summary>
        public static string TreeViewAddNode {
            get {
                return ResourceManager.GetString("TreeViewAddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Tree.
        /// </summary>
        public static string TreeViewDeleteTree {
            get {
                return ResourceManager.GetString("TreeViewDeleteTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort By.
        /// </summary>
        public static string TreeViewSortBy {
            get {
                return ResourceManager.GetString("TreeViewSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Tree View.
        /// </summary>
        public static string TreeViewToggleButton {
            get {
                return ResourceManager.GetString("TreeViewToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Results have been found....
        /// </summary>
        public static string WelcomeFlavorText {
            get {
                return ResourceManager.GetString("WelcomeFlavorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Good Afternoon.
        /// </summary>
        public static string WelcomeGreetingAfternoon {
            get {
                return ResourceManager.GetString("WelcomeGreetingAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Good Evening.
        /// </summary>
        public static string WelcomeGreetingEvening {
            get {
                return ResourceManager.GetString("WelcomeGreetingEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Good Morning.
        /// </summary>
        public static string WelcomeGreetingMorning {
            get {
                return ResourceManager.GetString("WelcomeGreetingMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Good Night.
        /// </summary>
        public static string WelcomeGreetingNight {
            get {
                return ResourceManager.GetString("WelcomeGreetingNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a New Forest.
        /// </summary>
        public static string WelcomeNewButton {
            get {
                return ResourceManager.GetString("WelcomeNewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open existing Forest.
        /// </summary>
        public static string WelcomeOpenButton {
            get {
                return ResourceManager.GetString("WelcomeOpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save As....
        /// </summary>
        public static string WelcomeSaveAs {
            get {
                return ResourceManager.GetString("WelcomeSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What&apos;s New.
        /// </summary>
        public static string WelcomeWhatsNew {
            get {
                return ResourceManager.GetString("WelcomeWhatsNew", resourceCulture);
            }
        }
    }
}
