//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogueForest.Localization.Strings {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DialogueForest.Localization.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DialogueForest.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string ButtonCancelText {
            get {
                return ResourceManager.GetString("ButtonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string ButtonDeleteText {
            get {
                return ResourceManager.GetString("ButtonDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string ButtonNoText {
            get {
                return ResourceManager.GetString("ButtonNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        public static string ButtonOKText {
            get {
                return ResourceManager.GetString("ButtonOKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string ButtonYesText {
            get {
                return ResourceManager.GetString("ButtonYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Queue as Playlist.
        /// </summary>
        public static string ContextMenuAddQueueToPlaylist {
            get {
                return ResourceManager.GetString("ContextMenuAddQueueToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add to Playlist.
        /// </summary>
        public static string ContextMenuAddToPlaylist {
            get {
                return ResourceManager.GetString("ContextMenuAddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add to Queue.
        /// </summary>
        public static string ContextMenuAddToQueue {
            get {
                return ResourceManager.GetString("ContextMenuAddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Queue.
        /// </summary>
        public static string ContextMenuClearQueue {
            get {
                return ResourceManager.GetString("ContextMenuClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Playlist.
        /// </summary>
        public static string ContextMenuDeletePlaylist {
            get {
                return ResourceManager.GetString("ContextMenuDeletePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play.
        /// </summary>
        public static string ContextMenuPlay {
            get {
                return ResourceManager.GetString("ContextMenuPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove from Playlist.
        /// </summary>
        public static string ContextMenuRemoveFromPlaylist {
            get {
                return ResourceManager.GetString("ContextMenuRemoveFromPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove from Queue.
        /// </summary>
        public static string ContextMenuRemoveFromQueue {
            get {
                return ResourceManager.GetString("ContextMenuRemoveFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View Album.
        /// </summary>
        public static string ContextMenuViewAlbum {
            get {
                return ResourceManager.GetString("ContextMenuViewAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Playlist?.
        /// </summary>
        public static string DeletePlaylistContentDialog {
            get {
                return ResourceManager.GetString("DeletePlaylistContentDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a piece of Dialogue.
        /// </summary>
        public static string EditorAddDialogue {
            get {
                return ResourceManager.GetString("EditorAddDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a reply Prompt.
        /// </summary>
        public static string EditorAddReply {
            get {
                return ResourceManager.GetString("EditorAddReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bold.
        /// </summary>
        public static string EditorBold {
            get {
                return ResourceManager.GetString("EditorBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Dialogue portion.
        /// </summary>
        public static string EditorDeleteDialogue {
            get {
                return ResourceManager.GetString("EditorDeleteDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Reply.
        /// </summary>
        public static string EditorDeleteReply {
            get {
                return ResourceManager.GetString("EditorDeleteReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UNUSEDD.
        /// </summary>
        public static string EditorEmptyDialogue {
            get {
                return ResourceManager.GetString("EditorEmptyDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replies to this dialogue will show up here, if you add any..
        /// </summary>
        public static string EditorEmptyReplies {
            get {
                return ResourceManager.GetString("EditorEmptyReplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text Color.
        /// </summary>
        public static string EditorFontColor {
            get {
                return ResourceManager.GetString("EditorFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dialogue.
        /// </summary>
        public static string EditorHeaderDialogue {
            get {
                return ResourceManager.GetString("EditorHeaderDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Metadata.
        /// </summary>
        public static string EditorHeaderMetadata {
            get {
                return ResourceManager.GetString("EditorHeaderMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prompts.
        /// </summary>
        public static string EditorHeaderReply {
            get {
                return ResourceManager.GetString("EditorHeaderReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italic.
        /// </summary>
        public static string EditorItalic {
            get {
                return ResourceManager.GetString("EditorItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accusam consetetur ut accusam et gubergren augue diam enim dolor at nulla ea ipsum diam et lobortis. Et no rebum odio takimata nulla nisl takimata iriure sit aliquyam eirmod nulla sit. Magna justo consetetur takimata..
        /// </summary>
        public static string EditorPlaceholderText {
            get {
                return ResourceManager.GetString("EditorPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to Linked Dialogue.
        /// </summary>
        public static string EditorReplyGoToLinked {
            get {
                return ResourceManager.GetString("EditorReplyGoToLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Linked to:.
        /// </summary>
        public static string EditorReplyLinkedTo {
            get {
                return ResourceManager.GetString("EditorReplyLinkedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magna ea feugiat labore diam diam assum amet nibh vero sea eirmod magna takimata eum illum. Labore et nonumy vulputate lorem zzril erat kasd eu no sed laoreet duo labore et diam eos..
        /// </summary>
        public static string EditorReplyPlaceholderText {
            get {
                return ResourceManager.GetString("EditorReplyPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show in Tree.
        /// </summary>
        public static string EditorShowInTree {
            get {
                return ResourceManager.GetString("EditorShowInTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Underline.
        /// </summary>
        public static string EditorUnderline {
            get {
                return ResourceManager.GetString("EditorUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I can&apos;t jam to this..
        /// </summary>
        public static string EmptyPlaylistTitle {
            get {
                return ResourceManager.GetString("EmptyPlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Why don&apos;t you add some music?.
        /// </summary>
        public static string EmptyQueueDesc {
            get {
                return ResourceManager.GetString("EmptyQueueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All is quiet now..
        /// </summary>
        public static string EmptyQueueTitle {
            get {
                return ResourceManager.GetString("EmptyQueueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Tracks found on Server..
        /// </summary>
        public static string EmptySearchDesc {
            get {
                return ResourceManager.GetString("EmptySearchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Funky Fresh Search!.
        /// </summary>
        public static string EmptySearchTitle {
            get {
                return ResourceManager.GetString("EmptySearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Dialogue Nodes will show up here. 
        ///You can create Nodes in the Dialogue Trees on the left side..
        /// </summary>
        public static string EmptyViewDocumentsDesc {
            get {
                return ResourceManager.GetString("EmptyViewDocumentsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Let&apos;s get writing!.
        /// </summary>
        public static string EmptyViewDocumentsTitle {
            get {
                return ResourceManager.GetString("EmptyViewDocumentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Dialogue will show up here.
        ///Click on the &quot;+&quot; button to add some!.
        /// </summary>
        public static string EmptyViewTreeDesc {
            get {
                return ResourceManager.GetString("EmptyViewTreeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Talkin&apos; yet..
        /// </summary>
        public static string EmptyViewTreeTitle {
            get {
                return ResourceManager.GetString("EmptyViewTreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t add Album: {0}.
        /// </summary>
        public static string ErrorAddingAlbum {
            get {
                return ResourceManager.GetString("ErrorAddingAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t clear queue!.
        /// </summary>
        public static string ErrorCantClearCache {
            get {
                return ResourceManager.GetString("ErrorCantClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: {0}.
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid MPD Response..
        /// </summary>
        public static string ErrorInvalidMPDResponse {
            get {
                return ResourceManager.GetString("ErrorInvalidMPDResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid password.
        /// </summary>
        public static string ErrorPassword {
            get {
                return ResourceManager.GetString("ErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error trying to play the MPD server&apos;s httpd stream: {0}.
        /// </summary>
        public static string ErrorPlayingMPDStream {
            get {
                return ResourceManager.GetString("ErrorPlayingMPDStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t play content: {0}.
        /// </summary>
        public static string ErrorPlayingTrack {
            get {
                return ResourceManager.GetString("ErrorPlayingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à parameter must be an Enum name!.
        /// </summary>
        public static string ExceptionEnumToBooleanConverterParameterMustBeAnEnumName {
            get {
                return ResourceManager.GetString("ExceptionEnumToBooleanConverterParameterMustBeAnEnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à value must be an Enum!.
        /// </summary>
        public static string ExceptionEnumToBooleanConverterValueMustBeAnEnum {
            get {
                return ResourceManager.GetString("ExceptionEnumToBooleanConverterValueMustBeAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File name is null or empty. Specify a valid file name.
        /// </summary>
        public static string ExceptionSettingsStorageExtensionsFileNameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionSettingsStorageExtensionsFileNameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All pages opened in a new window must subscribe to the Released Event..
        /// </summary>
        public static string ExceptionViewLifeTimeControlMissingReleasedSubscription {
            get {
                return ResourceManager.GetString("ExceptionViewLifeTimeControlMissingReleasedSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This view is being disposed..
        /// </summary>
        public static string ExceptionViewLifeTimeControlViewDisposal {
            get {
                return ResourceManager.GetString("ExceptionViewLifeTimeControlViewDisposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à David Bowie is credited with playing the Stylophone on his 1969 debut hit song &quot;Space Oddity&quot; and also for his 2002 album Heathen track titled &quot;Slip Away,&quot; as well as on the song &quot;Heathen (The Rays)&quot;..
        /// </summary>
        public static string FirstRunFlavorText {
            get {
                return ResourceManager.GetString("FirstRunFlavorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To get started, please visit the Settings page to key in your MPD server&apos;s URL and port.
        ///Keep in mind Stylophone can send usage data to help diagnose bugs. 
        ///If you&apos;re not okay with this, you can disable telemetry in the Settings.
        ///Hope you enjoy using the application!  
        ///.
        /// </summary>
        public static string FirstRunText {
            get {
                return ResourceManager.GetString("FirstRunText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to Stylophone!.
        /// </summary>
        public static string FirstRunTitle {
            get {
                return ResourceManager.GetString("FirstRunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        public static string NavigationExport {
            get {
                return ResourceManager.GetString("NavigationExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        public static string NavigationFile {
            get {
                return ResourceManager.GetString("NavigationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Forest.
        /// </summary>
        public static string NavigationNew {
            get {
                return ResourceManager.GetString("NavigationNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Tree.
        /// </summary>
        public static string NavigationNewTree {
            get {
                return ResourceManager.GetString("NavigationNewTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notes.
        /// </summary>
        public static string NavigationNotes {
            get {
                return ResourceManager.GetString("NavigationNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        public static string NavigationOpen {
            get {
                return ResourceManager.GetString("NavigationOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Pins.
        /// </summary>
        public static string NavigationPins {
            get {
                return ResourceManager.GetString("NavigationPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string NavigationSave {
            get {
                return ResourceManager.GetString("NavigationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string NavigationSettings {
            get {
                return ResourceManager.GetString("NavigationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trash.
        /// </summary>
        public static string NavigationTrash {
            get {
                return ResourceManager.GetString("NavigationTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dialogue Trees.
        /// </summary>
        public static string NavigationTrees {
            get {
                return ResourceManager.GetString("NavigationTrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added to Playlist {0}!.
        /// </summary>
        public static string NotificationAddedToPlaylist {
            get {
                return ResourceManager.GetString("NotificationAddedToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added to Queue!.
        /// </summary>
        public static string NotificationAddedToQueue {
            get {
                return ResourceManager.GetString("NotificationAddedToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Album art cache has been deleted..
        /// </summary>
        public static string NotificationCacheDeleted {
            get {
                return ResourceManager.GetString("NotificationCacheDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The database is already being updated..
        /// </summary>
        public static string NotificationDbAlreadyUpdating {
            get {
                return ResourceManager.GetString("NotificationDbAlreadyUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database update started..
        /// </summary>
        public static string NotificationDbUpdateStarted {
            get {
                return ResourceManager.GetString("NotificationDbUpdateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Track is currently playing..
        /// </summary>
        public static string NotificationNoTrackPlaying {
            get {
                return ResourceManager.GetString("NotificationNoTrackPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No tracks loaded yet..
        /// </summary>
        public static string NotificationNoTracksLoaded {
            get {
                return ResourceManager.GetString("NotificationNoTracksLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Now Playing {0}.
        /// </summary>
        public static string NotificationNowPlayingTrack {
            get {
                return ResourceManager.GetString("NotificationNowPlayingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Off.
        /// </summary>
        public static string OffText {
            get {
                return ResourceManager.GetString("OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On.
        /// </summary>
        public static string OnText {
            get {
                return ResourceManager.GetString("OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thanks for using DialogueForest! Would you like to rate the app on the Store? 
        ///(We won&apos;t ask again. 🙏).
        /// </summary>
        public static string RateAppPromptText {
            get {
                return ResourceManager.GetString("RateAppPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rate the Application.
        /// </summary>
        public static string RateAppPromptTitle {
            get {
                return ResourceManager.GetString("RateAppPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Albums.
        /// </summary>
        public static string SearchAlbumsToggle {
            get {
                return ResourceManager.GetString("SearchAlbumsToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Artists.
        /// </summary>
        public static string SearchArtistsToggle {
            get {
                return ResourceManager.GetString("SearchArtistsToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search for &quot;{0}&quot; on the server....
        /// </summary>
        public static string SearchGoToDetail {
            get {
                return ResourceManager.GetString("SearchGoToDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Results have been found....
        /// </summary>
        public static string SearchNoResultsTitle_Text {
            get {
                return ResourceManager.GetString("SearchNoResultsTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search....
        /// </summary>
        public static string SearchPlaceholderText {
            get {
                return ResourceManager.GetString("SearchPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tracks.
        /// </summary>
        public static string SearchTracksToggle {
            get {
                return ResourceManager.GetString("SearchTracksToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search Nodes....
        /// </summary>
        public static string SearchTreePlaceholderText {
            get {
                return ResourceManager.GetString("SearchTreePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About this application.
        /// </summary>
        public static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MPD Client for the Universal Windows Platform, based on MpcNET..
        /// </summary>
        public static string SettingsAboutText {
            get {
                return ResourceManager.GetString("SettingsAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analytics.
        /// </summary>
        public static string SettingsAnalytics {
            get {
                return ResourceManager.GetString("SettingsAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow Stylophone to send crash and analytics reports.
        /// </summary>
        public static string SettingsAnalyticsText {
            get {
                return ResourceManager.GetString("SettingsAnalyticsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This setting will apply after restarting the app..
        /// </summary>
        public static string SettingsApplyOnRestart {
            get {
                return ResourceManager.GetString("SettingsApplyOnRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Cache.
        /// </summary>
        public static string SettingsClearCache {
            get {
                return ResourceManager.GetString("SettingsClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear the local album art cache.
        /// </summary>
        public static string SettingsClearCacheDescription {
            get {
                return ResourceManager.GetString("SettingsClearCacheDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personalization.
        /// </summary>
        public static string SettingsCustomization {
            get {
                return ResourceManager.GetString("SettingsCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database and Album Art.
        /// </summary>
        public static string SettingsDatabase {
            get {
                return ResourceManager.GetString("SettingsDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source Code, License and Privacy Statement.
        /// </summary>
        public static string SettingsGithub {
            get {
                return ResourceManager.GetString("SettingsGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://github.com/Difegue/Stylophone.
        /// </summary>
        public static string SettingsGithubLink {
            get {
                return ResourceManager.GetString("SettingsGithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local Playback available.
        /// </summary>
        public static string SettingsLocalPlaybackAvailable {
            get {
                return ResourceManager.GetString("SettingsLocalPlaybackAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local Playback.
        /// </summary>
        public static string SettingsLocalPlaybackHeader {
            get {
                return ResourceManager.GetString("SettingsLocalPlaybackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylophone can play your MPD Server&apos;s music stream.
        ///Enabling this option will show a second volume slider to control local volume..
        /// </summary>
        public static string SettingsLocalPlaybackText {
            get {
                return ResourceManager.GetString("SettingsLocalPlaybackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t find an MPD server at this address!.
        /// </summary>
        public static string SettingsNoServerError {
            get {
                return ResourceManager.GetString("SettingsNoServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MPD Server.
        /// </summary>
        public static string SettingsServer {
            get {
                return ResourceManager.GetString("SettingsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hostname.
        /// </summary>
        public static string SettingsServerHost {
            get {
                return ResourceManager.GetString("SettingsServerHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string SettingsServerPassword {
            get {
                return ResourceManager.GetString("SettingsServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port.
        /// </summary>
        public static string SettingsServerPort {
            get {
                return ResourceManager.GetString("SettingsServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Theme.
        /// </summary>
        public static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dark.
        /// </summary>
        public static string SettingsThemeDark {
            get {
                return ResourceManager.GetString("SettingsThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System default.
        /// </summary>
        public static string SettingsThemeDefault {
            get {
                return ResourceManager.GetString("SettingsThemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Light.
        /// </summary>
        public static string SettingsThemeLight {
            get {
                return ResourceManager.GetString("SettingsThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UI Density.
        /// </summary>
        public static string SettingsUIDensity {
            get {
                return ResourceManager.GetString("SettingsUIDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compact.
        /// </summary>
        public static string SettingsUIDensityCompact {
            get {
                return ResourceManager.GetString("SettingsUIDensityCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normal.
        /// </summary>
        public static string SettingsUIDensityNormal {
            get {
                return ResourceManager.GetString("SettingsUIDensityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        public static string SettingsUpdateDatabase {
            get {
                return ResourceManager.GetString("SettingsUpdateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This operation might take the server some time to complete..
        /// </summary>
        public static string SettingsUpdateDbDesc {
            get {
                return ResourceManager.GetString("SettingsUpdateDbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Dialogue Node.
        /// </summary>
        public static string TreeViewAddNode {
            get {
                return ResourceManager.GetString("TreeViewAddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Tree.
        /// </summary>
        public static string TreeViewDeleteTree {
            get {
                return ResourceManager.GetString("TreeViewDeleteTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Graph Overview.
        /// </summary>
        public static string TreeViewGraphView {
            get {
                return ResourceManager.GetString("TreeViewGraphView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort By.
        /// </summary>
        public static string TreeViewSortBy {
            get {
                return ResourceManager.GetString("TreeViewSortBy", resourceCulture);
            }
        }
    }
}
